### ISSUE TITLE
Allow disabling endpoints

### ISSUE THREAD

**Issue by Molter73** [bpfd-dev/bpfd#418]
Since #410 was merged, bpfd is now listening on both a Unix and a TCP socket and the only configuration possible is where they actually listen on. It'd be great if we could have more control over what endpoints bpfd listens on. There are a few ways we could achieve this, off the top of my head these are some of them:

#### Make the default behavior to not listen on the TCP socket
This would be the simplest solution, make the configuration for TCP socket required for bpfd to listen on it. We could apply the same logic to the unix socket, but since bpfd needs to listen on at least one endpoint, I think it makes sense to always listen on the default unix socket.

#### Add an `enabled` field for each endpoint
We could add a `tcp_enabled` and a `unix_enabled` field to the `grpc.endpoint` configuration, they would default to `true` and setting them to `false` would cause bpfd to not open the specified endpoint. Though this achieves the objective of being able to disable bpfd from listening on certain types of endpoints, the naming is not the most friendly in my opinion.

Another option in this same idea is to split the `grpc.endpoint` section into `grpc.endpoint.unix` and `grpc.endpoint.tcp`, each of them having its own fields, looking something like this:
```toml
[grpc.endpoint.tcp]
address = "::1"
port = 50051
enabled = false

[grpc.endpoint.unix]
path = "/run/bpfd/bpfd.sock"
enabled = true
```

#### Unify endpoint configuration and allow more of them
Building a little on top of the previous example, we could also unify endpoint configuration and turn it from a simple table to an array of tables, looking something like this:
```toml
[[grpc.endpoint]]
type = "tcp"
enabled = true
address = "::1"
port = 50051

[[grpc.endpoint]]
type = "tcp"
enabled = false
address = "127.0.0.1"
port = 50051

[[grpc.endpoint]]
type = "unix"
enabled = true
address = "/run/bpfd/bpfd.sock"
port = 1  # This could issue a warning and ignore it when creating the server.
```
As stated on a previous point, not adding any endpoints in this example would cause bpfd to only listen on the default unix socket.

I admit this last option could be a bit overkill, but I still wanted to put it out there. There also might be a way to not add the `type` field and instead have serde desarialize an enum based on whether we have `address` and `port` or `path` in the element, but I'm not sure that's the case and don't want to delve deeper into implementation details right now.

P.S: Sorry for the wall of text, I got a little carried away.

**Comment by dave-tucker** [comment]
FWIW I like the "array of tables" idea. It more cleanly expresses what we want.
TLS should probably belong to a given gRPC endpoint, since we don't do TLS over unix socket.

**Comment by Molter73** [comment]
> TLS should probably belong to a given gRPC endpoint, since we don't do TLS over unix socket.

This has the potential to become quite verbose, since TOML doesn't provide a way to re-use sections, the same TLS block would be needed over multiple tcp configurations, something like this:
```toml
[[grpc.endpoints]]
type = "tcp"
enabled = true
address = "::1"
port = 50051
ca_cert = "/etc/bpfd/certs/ca/ca.pem"
cert = "/etc/bpfd/certs/bpfd/bpfd.pem"
key = "/etc/bpfd/certs/bpfd/bpfd.key"
client_cert = "/etc/bpfd/certs/bpfd-client/bpfd-client.pem"
client_key = "/etc/bpfd/certs/bpfd-client/bpfd-client.key"

[[grpc.endpoints]]
type = "tcp"
enabled = true
address = "127.0.0.1"
port = 50051
ca_cert = "/etc/bpfd/certs/ca/ca.pem"
cert = "/etc/bpfd/certs/bpfd/bpfd.pem"
key = "/etc/bpfd/certs/bpfd/bpfd.key"
client_cert = "/etc/bpfd/certs/bpfd-client/bpfd-client.pem"
client_key = "/etc/bpfd/certs/bpfd-client/bpfd-client.key"
```

I guess one alternative could be to have a global TLS configuration like the one we have now and TCP sockets that don't specify TLS configuration can fallback to that.
