### ISSUE TITLE
Run examples based on version tag

### ISSUE THREAD

**Issue by Billy99** [bpfd-dev/bpfd#514]
The goal is to be able to run a tagged version of the examples using kustomize:
`TAG=v0.2.0 make deploy-go-xdp-counter`

Kustomize is not setup to do the above (based on a variable). Kustomize is more static. Below are 3 examples of how it could be done, each with pros and cons.

**The Kustomize way (tracepoint):**
Most of the Kustomize examples have 2-3 static deployments, like `prod`, `staging`, `test`. There is a base directory with the default yaml, then each deployment has it's own directory with overrides. This is modeled in the tracepoint:
```
.
├── go-tracepoint-counter-bytecode
│   ├── base
│   │   ├── go-tracepoint-counter-bytecode.yaml
│   │   └── kustomization.yaml
│   ├── v0.2.0
│   │   └── kustomization.yaml
│   ├── v0.2.1
│   │   └── kustomization.yaml
│   ├── v0.2.2
│   │   └── kustomization.yaml
│   ├── v0.2.3
│   │   └── kustomization.yaml
│   ├── v0.3.0
│   │   └── kustomization.yaml
│   └── v0.3.1
│       └── kustomization.yaml
├── go-tracepoint-counter-userspace
│   ├── base
│   │   ├── go-tracepoint-counter-userspace.yaml
│   │   └── kustomization.yaml
│   ├── v0.2.0
│   │   └── kustomization.yaml
│   ├── v0.2.1
│   │   └── kustomization.yaml
│   ├── v0.2.2
│   │   └── kustomization.yaml
│   ├── v0.2.3
│   │   └── kustomization.yaml
│   ├── v0.3.0
│   │   └── kustomization.yaml
│   └── v0.3.1
│       └── kustomization.yaml
```

The `go-tracepoint-counter-bytecode/base/go-tracepoint-counter-bytecode.yaml` and `go-tracepoint-counter-userspace/base/go-tracepoint-counter-userspace.yaml` are the exact same yaml files as today. The `base/kustomization.yaml` files just point to the resource:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - go-tracepoint-counter-bytecode.yaml
```

The versions specific `kustomization.yaml` files are cut and paste of the previous with the version tag changed:
```
$ cat go-tracepoint-counter-bytecode/v0.2.0/kustomize.yaml`
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
# Change tag on url (which is an image) to new value
patches:
  - target:
      kind: TracepointProgram
      name: "go-tracepoint-counter-example"
    patch: |-
      - op: replace
        path: "/spec/bytecode/image/url"
        value: quay.io/bpfd-bytecode/go-tracepoint-counter:v0.2.0
```
```
$ cat go-tracepoint-counter-userspace/v0.2.0/kustomize.yaml`
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
# Change tag on url (which is an image) to new value
images:
- name: quay.io/bpfd-userspace/go-tracepoint-counter
  newName: quay.io/bpfd-userspace/go-tracepoint-counter
  newTag: v0.2.0
```

The `Makefile` looks like:
```
.PHONY: deploy-go-tracepoint-counter
deploy-go-tracepoint-counter: kustomize ## Deploy go-tracepoint-counter to the cluster specified in ~/.kube/config.
ifdef TAG_TR
	$(KUSTOMIZE) build config/go-tracepoint-counter-bytecode/$(TAG_TR) | kubectl apply -f -
	$(KUSTOMIZE) build config/go-tracepoint-counter-userspace/$(TAG_TR) | kubectl apply -f -
else
	kubectl apply -f config/go-tracepoint-counter-bytecode/base/go-tracepoint-counter-bytecode.yaml
	kubectl apply -f config/go-tracepoint-counter-userspace/base/go-tracepoint-counter-userspace.yaml
endif
```

PROS: The Kustomize way of doing it.
CONS: As the number of releases grow, it will become unwieldy.

**Use Environment Variable in base yaml file (xdp):**
Following https://mbuffa.github.io/tips/20210720-kustomize-environment-variables/, use an environment variable in the base yaml, then write the variable value passed into the `make` command to a local file, then Kustomize reads the file and creates a ConfigMap which it uses to modify the base yaml.
```
.
├── go-xdp-counter-bytecode
│   ├── env-var-transformer.yaml
│   ├── go-xdp-counter-bytecode.yaml
│   └── kustomization.yaml
└── go-xdp-counter-userspace
    ├── env-var-transformer.yaml
    ├── go-xdp-counter-userspace.yaml
    └── kustomization.yaml
```

The base yaml files have an environment variable in place of the image:
```
cat go-xdp-counter-bytecode/go-xdp-counter-bytecode.yaml
apiVersion: bpfd.io/v1alpha1
kind: XdpProgram
:
spec:
  :
  bytecode:
    image:
      url: $(URL_BC)
```
```
cat go-xdp-counter-userspace/go-xdp-counter-userspace.yaml
---
apiVersion: apps/v1
kind: DaemonSet
:
spec:
  template:
    spec:
      containers:
      - name: go-xdp-counter
        image: $(URL_US)
```
The `env-var-transformer.yaml` indicate to Kustomize which field is being transforming:
```
cat go-xdp-counter-bytecode/env-var-transformer.yaml
varReference:
  - kind: XdpProgram
    path: spec/bytecode/image/url
```
```
cat go-xdp-counter-userspace/env-var-transformer.yaml
varReference:
  - kind: DaemonSet
    path: spec/template/spec/containers/image
```
The `kustomization.yaml` indicate to Kustomize how to create the ConfigMap and the variable name:
```
cat go-xdp-counter-bytecode/kustomization.yaml
resources:
- go-xdp-counter-bytecode.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - env-var-transformer.yaml
configMapGenerator:
- name: bpfd-examples-kustomize-env-xdp-bc
  envs: [url-bc.env]
  behavior: create
vars:
- name: URL_BC
  objref:
    kind: ConfigMap
    name: bpfd-examples-kustomize-env-xdp-bc
    apiVersion: v1
  fieldref:
    fieldpath: data.URL_BC
```
```
cat go-xdp-counter-userspace/kustomization.yaml
resources:
- go-xdp-counter-userspace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - env-var-transformer.yaml
configMapGenerator:
- name: bpfd-examples-kustomize-env-xdp-us
  envs: [url-us.env]
  behavior: create
vars:
- name: URL_US
  objref:
    kind: ConfigMap
    name: bpfd-examples-kustomize-env-xdp-us
    apiVersion: v1
  fieldref:
    fieldpath: data.URL_US
```

The `Makefile` takes the input environment variable and writes it to a file:
```
.PHONY: deploy-go-xdp-counter
deploy-go-xdp-counter: kustomize ## Deploy go-xdp-counter to the cluster specified in ~/.kube/config.
	echo URL_BC="quay.io/bpfd-bytecode/go-xdp-counter:$(TAG)" > config/go-xdp-counter-bytecode/url-bc.env
	$(KUSTOMIZE) build config/go-xdp-counter-bytecode | kubectl apply -f -
	echo URL_US="quay.io/bpfd-userspace/go-xdp-counter:$(TAG)" > config/go-xdp-counter-userspace/url-us.env
	$(KUSTOMIZE) build config/go-xdp-counter-userspace | kubectl apply -f -
```

PROS: Less file management compared to the previous example
CONS: The base yamls can't be run outside of `make deploy` because they ow have an environment variable embedded in them.

**Use Environment Variable in kustomization.yaml (tc):**
This example places the environment variable in a kustomization.yaml.overlay file, runs `sed` to replace the variable, then runs the output through Kustomize. So the base yaml files are unchanged.
```
.
├── go-tc-counter-bytecode
│   ├── go-tc-counter-bytecode.yaml
│   └── kustomization.yaml.overlay
├── go-tc-counter-userspace
│   ├── go-tc-counter-userspace.yaml
│   └── kustomization.yaml.overlay
```

The `kustomization.yaml.overlay` files (added the .overlay since they can't be run through Kustomize as is, we can come up with another extension if desired) contain the environment variable:
```
cat go-tc-counter-bytecode/kustomization.yaml.overlay
resources:
- go-tc-counter-bytecode.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Change tag on url (which is an image) to new value
patches:
  - patch: |-
      - op: replace
        path: "/spec/bytecode/image/url"
        value: URL_BC
    target:
      kind: TcProgram
      name: "go-tc-counter-example"
``` 
```
cat go-tc-counter-userspace/kustomization.yaml.overlay
resources:
- go-tc-counter-userspace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Change tag on url (which is an image) to new value
images:
- name: quay.io/bpfd-userspace/go-tc-counter
  newName: $(URL_US)
  newTag: $(TAG_US)
```

Then `sed` is used in the `Makefile` to make a tmp version of the kustomization.yaml:
```
.PHONY: deploy-go-tc-counter
deploy-go-tc-counter: kustomize ## Deploy go-tc-counter to the cluster specified in ~/.kube/config.
ifdef TAG_TC
	sed 's@URL_BC@quay.io/bpfd-bytecode/go-tc-counter:$(TAG_TC)@' config/go-tc-counter-bytecode/kustomization.yaml.overlay > config/go-tc-counter-bytecode/kustomization.yaml
	$(KUSTOMIZE) build config/go-tc-counter-bytecode | kubectl apply -f -
	rm config/go-tc-counter-bytecode/kustomization.yaml
	
	sed 's@URL_US@quay.io/bpfd-userspace/go-tc-counter:$(TAG_TC)@' config/go-tc-counter-userspace/kustomization.yaml.overlay > config/go-tc-counter-usersapce/kustomization.yaml
	$(KUSTOMIZE) build config/go-tc-counter-userspace | kubectl apply -f -
	rm config/go-tc-counter-userspace/kustomization.yaml
else
	kubectl apply -f config/go-tc-counter-bytecode/go-tc-counter-bytecode.yaml
	kubectl apply -f config/go-tc-counter-userspace/go-tc-counter-userspace.yaml
endif
```

PROS: Base yaml files are unchanged, so they can be run outside of `make deploy`.
CONS: Using `sed` for part of the transformation.
